name: 'Check App Version'
description: 'Check the deployed application version by calling the health endpoint.'

inputs:
  app_version:
    description: 'app version'
    required: true
  host_name:
    description: 'app hostname'
    required: true
  uri_path:
    description: 'app health path'
    required: true
    default: "/api/v1/internal/health"

runs:
  using: 'composite'
  steps:
    - name: Install jq and curl
      shell: bash
      run: |
        apt-get update
        apt-get install -y jq curl
      
    - name: Check App Version
      shell: bash
      run: |
        sleep 20
        CHECK_VER=false
        for (( i = 1; i <= 15; ++i ))
          do
            echo "Checking service..."
            RUNNING_VERSION=$(curl -m10 -s https://${{ inputs.host_name }}${{ inputs.uri_path }} | jq -r '.version')
            if [[ ${RUNNING_VERSION} == ${{ inputs.app_version }} ]]
              then
                CHECK_VER=true
                break
            fi
            sleep 10
          done

        if [[ ${CHECK_VER} == true ]]
          then
            echo "The version: ${{ inputs.app_version }} has been deployed with success"
            exit 0
          else
            echo -e "The deployment has timed out or failed.\nThe running version: ${RUNNING_VERSION} is different from the deployed version: ${{ inputs.app_version }}.\nPlease check logs and pod status in Kubernetes."
            exit 1
        fi
        
